source 'http://rubygems.org'

gem 'sinatra'
gem 'activerecord', '~> 4.2', '>= 4.2.6', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem "rake", ">= 12.3.3"
gem 'require_all'
gem 'sqlite3', '~> 1.3.6'
gem 'shotgun'
gem 'pry'
gem 'pry-nav'
gem 'bcrypt'
gem 'sinatra-flash'
gem 'json'
gem 'chartkick'
gem 'alphavantagerb', '1.3.2'
gem 'iex-ruby-client'
gem 'database_cleaner'
gem 'email_validator'

group :development, :test do
  gem 'tux'
  gem 'pry'
  gem 'rspec'
  gem 'capybara'
  gem 'rack-test'
  gem 'database_cleaner-active_record'
  gem 'database_cleaner-redis'
  gem 'yard-sinatra'
  gem 'yard-ghpages'
end
